Feature/error handling
ricom/toolbox-frontend pull request #11
Opened 2021-09-15 20:34 UTC by nic-schi

**Added the following...**
1. Added an ErrorPages component that will manage all of the existing error pages.
2. Added an ErrorPage component that can be used to display a customized error page.
3. Added an GeneralError component, that will display an error page saying there was an general error.
4. Added Error pages 404 (Not found), 403 (Forbidden) and 500 (Database connection not resolved)
5. Reworked the index.tsx. The page will now display an loader if needed, and then replace the whole page with all the content and routers.
6. Reworked some scss and appearance
7. Formatted code

**Note:** Any route that doesnt exist e.g. "/idontexist" will now display the 404 Errorpage.

2021-09-16 06:50 UTC, ma1160 approved these changes

2021-09-16 08:38 UTC, Geist5000 commented
General Error Component isn't used, is this intentional?

2021-09-16 08:38 UTC, Geist5000 requested changes

2021-09-17 07:50 UTC, Geist5000 approved these changes

2021-09-18 21:16 UTC, merged