Coordinate system
ricom/toolbox-frontend pull request #66
Opened 2022-07-20 18:30 UTC by nic-schi

### Coordinate System
A Coordinate-System can now be created using an React-Component. This was one of the required functionalities for the portfolio analysis. The Coordinate-System then looks like the following:

![image](https://user-images.githubusercontent.com/43421445/180055074-24bb49ec-029c-4eea-a065-3e9cae9c47cf.png)

By hovering over an Point in the System an Tooltip will open up and the X- and Y-Values will be displayed.

![4](https://user-images.githubusercontent.com/43421445/180055379-0a6c3ad0-f952-4d97-b2c3-04e5bb6f1372.gif)

The X And Y Values are written in an table under the Coordinate System.

![image](https://user-images.githubusercontent.com/43421445/180055200-e6747747-718a-4a1d-b8ef-bb8c8fe60c15.png)

2022-07-21 11:08 UTC, Geist5000 requested changes
There is documentation missing. In my oppinion at least the props should get documented

2022-07-21 11:08 UTC, Geist5000 commented on src/general-components/CoordinateSystem/ValueRenderer/ValueRenderer.tsx
> +abstract class ValueRenderer {
I think this should be an interface

2022-07-21 11:09 UTC, Geist5000 commented on src/general-components/CoordinateSystem/CoordinateSystem.tsx
> +                                                </Tooltip>
This is just an information.

2022-07-21 15:17 UTC, ma1160 commented on src/general-components/CoordinateSystem/CoordinateSystem.tsx
> +                                                </Tooltip>
Will be looked at a later date.

2022-07-22 08:36 UTC, Geist5000 approved these changes
Looks good to me!

2022-07-27 15:52 UTC, merged